### ISSUE TITLE
The pdom.dev web site crashed my Windows 11 PC

### ISSUE THREAD

**Issue by russellgilbert** [pdomdev/pdom#1]
I saw this project on TLDR Web Dev so I went to pdom.dev and watched the two graphs for about 10 seconds or so, seeing that the "after" animation was spinning quickly while the "before" animation was slowing down. The fans started spinning up on my machine, then my mouse froze, and then I got a green crash screen saying, "Your Windows Insider Build ran into a problem and needs to restart." The Stop code was CLOCK_WATCHDOG_TIMEOUT. I had to do a hard reset after that.

Info about my PC:
OS: Windows 11 Pro version 24H2 build 26100.1150.
CPU: Intel Core i9-11900K.
Browser: Microsoft Edge Version 126.0.2592.87, Official build, 64-bit.

**Comment by jurienhamaker** [comment]
And for others it does little to nothing:
![firefox_B6UUhaeaZ8](https://github.com/pdomdev/pdom/assets/5418114/9d5fc4ad-d452-417d-b703-4102a92b5277)

**Comment by ashubham** [comment]
@jurienhamaker As stated in the Readme/homepage its currently only supported on Chrome/Edge because of browser limitations. Were you using on one of those browsers ?

**Comment by jurienhamaker** [comment]
> @jurienhamaker As stated in the Readme/homepage its currently only supported on Chrome/Edge because of browser limitations. Were you using on one of those browsers ?

This was only added after my screenshot... Besides, it did crash my pc nonetheless.
How about, if you don't support a browser, you don't run it at all? Besides that the left example is still crashing any other browser. I suggest limiting to 2m or so

Edit:
On a sidenote, I came here through daily.dev extension. This article from there did not mention nor warn anything about supported browsers.

**Comment by ashubham** [comment]
FWIW, a site being able to crash a browser/PC speaks more of the browser/PC than the site itself.

But, anyways we are fixing the demo to not run on unsupported browsers. Thanks!
